name: Publish Release Image

on:
    release:
        types: [published]

jobs:
    push:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: '9.0.x'

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  sep-tags: ;
                  tags: |
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}


            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Publish Container
              run: >
                  dotnet publish ./FosterRoster/FosterRoster.csproj
                  --configuration Release
                  --os linux
                  --arch x64
                  /t:PublishContainer
                  -p ContainerRegistry=docker.io
                  -p ContainerRepositoryName=melgish/foster-roster
                  -p ContainerImageTags='"${{ steps.meta.outputs.tags }}"'
